### ISSUE TITLE
Any possibility to support multiple `gatsby-theme-catalyst-blog` plugins, for different basePath

### ISSUE THREAD

**Issue by ghost** [ehowey/gatsby-starter-catalyst-blog#11]
Hi Eric, 

First of all, really like the framework that you designed! So I am trying to build up one based your vary plugins.

I came out idea to have multiple `-blog` plugins for different paths, similar like `gatsby-source-filesystem`. 

Tried with 2 `-blog` plugins, and it's shadowed by the other. Wondering if I did any config wrong?
```
{
      resolve: `gatsby-theme-catalyst-blog`,
      options: {
        basePath: `/backend`,
        contentPath: `content/backend`,
        assetPath: `content/backend-assets`,
        excerptLength: `280`,
        postListTitle: "Backend",
        displayPostListTitle: true,
      }
    },
    {
      resolve: `gatsby-theme-catalyst-blog`,
      options: {
        basePath: `/frontend`,
        contentPath: `content/frontend`,
        assetPath: `content/frontend-assets`,
        excerptLength: `280`,
        postListTitle: "Frontend",
        displayPostListTitle: true,
      }
    }
```

Thanks

**Comment by ehowey** [comment]
Hi @cuizhanming - thanks for the positive feedback.

I don't believe this is possible as I did not design it with multiple blogs in mind. 

I think you probably would need to fork the repo and you could copy/paste the blog theme and rename one "frontend-blog" and one "backend-blog" and that would probably work.  There is quite a bit going on in the blog theme as it is more of a "data" theme so has some opinions about structure and graphql format, etc. But I think if you did a careful find and replace you could probably get that working.  Does that make sense?

**Comment by ghost** [comment]
Thanks Eric! That makes sense.
